"""Pywebview-based desktop app — everything in one native window.

This replaces the tkinter GUI (zoho_video_renamer.gui). The whole flow —
folder pickers, API key entry, scan progress, review of matched videos,
approve/exclude, final rename — happens inside a single WKWebView (macOS)
/ WebView2 (Windows) / GTK (Linux) window. No external browser, no file
export step, no Terminal.

Architecture:
- `webview.create_window(...)` opens a native window pointing at FORM_HTML
- `Api` class is exposed as `window.pywebview.api.*` to the JavaScript
- The form's Start button calls `api.scan(...)` which runs in a worker
  thread and posts progress/completion back via `evaluate_js`
- When scan completes, the window is navigated (via `load_html`) to the
  review HTML (generated by `ui.write_review_html`), which detects
  `window.pywebview` and replaces its Export-JSON button with an in-place
  Approve-and-Rename button that calls back into `api.apply_renames(...)`
"""
from __future__ import annotations

import json
import os
import threading
from typing import Optional

import webview

from . import __version__, naming, ui
from . import apply as apply_mod
from .matcher import (
    match_videos_to_stills, pick_canonical_still,
    scan_stills, scan_videos, scan_videos_only,
)
from .thumbnailer import (
    batch_extract_video_frames, batch_make_still_thumbs,
    check_ffmpeg, extract_three_frames, safe_id,
)


FORM_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ZohoVideoRenamer</title>
<style>
  :root {
    --bg:#0f0f12; --bg2:#16161b; --panel:#1c1c22; --panel2:#25252d;
    --border:#2e2e38; --text:#ecedf2; --muted:#9396a3;
    --accent:#e6b35a; --good:#6ec077; --bad:#d97a6c;
  }
  * { box-sizing: border-box; }
  body {
    background: var(--bg); color: var(--text); margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size: 14px; line-height: 1.55;
  }
  .container { max-width: 720px; margin: 0 auto; padding: 32px 28px 40px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; color: var(--accent); display: flex; align-items: center; gap: 10px; }
  .sub { color: var(--muted); font-size: 13px; margin-bottom: 22px; }
  .field { margin-bottom: 16px; }
  .field label { display: block; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 6px; color: var(--text); }
  .field .hint { color: var(--muted); font-size: 11px; margin-top: 4px; }
  .row { display: flex; gap: 8px; }
  input[type="text"], input[type="password"], select {
    flex: 1; padding: 9px 12px; background: var(--bg2); color: var(--text);
    border: 1px solid var(--border); border-radius: 6px; font-size: 13px;
    font-family: inherit;
  }
  input:focus, select:focus { outline: none; border-color: var(--accent); }
  button {
    background: var(--panel2); color: var(--text); border: 1px solid var(--border);
    padding: 9px 14px; border-radius: 6px; font-size: 13px; cursor: pointer;
    font-family: inherit; font-weight: 600;
  }
  button:hover { background: var(--panel); }
  button.primary { background: var(--accent); color: #1a1a1d; border-color: var(--accent); }
  button.primary:hover { filter: brightness(1.08); }
  button.primary:disabled { background: #5a5a60; color: #aaa; cursor: not-allowed; }
  .checkbox-row { display: flex; align-items: center; gap: 10px; padding: 10px 12px; background: var(--panel); border-radius: 6px; margin-bottom: 16px; cursor: pointer; user-select: none; }
  .checkbox-row input { width: 16px; height: 16px; cursor: pointer; }
  .ai-box { padding: 16px; background: var(--panel); border: 1px solid var(--border); border-radius: 8px; margin-top: 8px; margin-bottom: 16px; }
  .ai-box h3 { margin: 0 0 6px; font-size: 13px; font-weight: 700; color: var(--accent); }
  .ai-box p { margin: 0 0 12px; color: var(--muted); font-size: 12px; }
  .log-area {
    margin-top: 18px; padding: 14px;
    background: var(--bg2); border-radius: 8px; border: 1px solid var(--border);
    font-family: 'JetBrains Mono', ui-monospace, Menlo, monospace;
    font-size: 11px; line-height: 1.55; color: var(--text);
    min-height: 100px; max-height: 280px; overflow-y: auto;
    white-space: pre-wrap;
  }
  .log-area .ok { color: var(--good); }
  .log-area .warn { color: var(--accent); }
  .log-area .err { color: var(--bad); }
  .actions { margin-top: 20px; display: flex; gap: 10px; }
  .stills-row.hidden { display: none; }
</style>
</head>
<body>
<div class="container">
  <h1><span>▶</span> ZohoVideoRenamer</h1>
  <div class="sub">Match videos to source stills, propose names with AI, review, then rename — all in one window.</div>

  <label class="checkbox-row">
    <input id="videos-only" type="checkbox" onchange="toggleStills()">
    <span><strong>Videos-only catalog mode</strong> — no stills folder, AI watches 3 frames per video</span>
  </label>

  <div class="field stills-row" id="stills-row">
    <label>Stills folder</label>
    <div class="row">
      <input id="stills" type="text" placeholder="Pick the folder with your source images" readonly>
      <button onclick="pickFolder('stills')">Browse…</button>
    </div>
  </div>

  <div class="field">
    <label>Videos folder</label>
    <div class="row">
      <input id="videos" type="text" placeholder="Pick the folder with your videos" readonly>
      <button onclick="pickFolder('videos')">Browse…</button>
    </div>
  </div>

  <div class="field">
    <label>Output / review folder</label>
    <div class="row">
      <input id="output" type="text" placeholder="Where temporary review files go (created if missing)" readonly>
      <button onclick="pickFolder('output')">Browse…</button>
    </div>
    <div class="hint">Defaults to ~/Desktop/video-rename-review</div>
  </div>

  <div class="ai-box">
    <h3>AI naming (optional, recommended)</h3>
    <p>Without an API key, names fall back to filenames. With a key, AI looks at each scene and proposes a 3-word descriptive name (~$0.005 per image).</p>
    <div class="row" style="margin-bottom: 8px;">
      <select id="provider" style="max-width: 200px;">
        <option value="">(none — use filenames)</option>
        <option value="anthropic">Anthropic Claude</option>
        <option value="openai">OpenAI GPT-4o</option>
      </select>
      <input id="api-key" type="password" placeholder="API key (sk-ant-... or sk-...)">
    </div>
  </div>

  <div class="field">
    <label>Apply mode (what to do with files when you click Approve & Rename)</label>
    <select id="operation">
      <option value="rename">Rename in place (default)</option>
      <option value="copy">Copy to new folder (originals kept)</option>
      <option value="move">Move to new folder</option>
    </select>
  </div>

  <div class="actions">
    <button id="start" class="primary" onclick="startScan()">▶ Start</button>
    <button onclick="openLastReview()">Open last review</button>
  </div>

  <div class="log-area" id="log">Ready. Pick folders + (optional) API key, then click Start.</div>
</div>

<script>
function toggleStills() {
  document.getElementById('stills-row').classList.toggle('hidden', document.getElementById('videos-only').checked);
}
async function pickFolder(id) {
  const path = await window.pywebview.api.pick_folder();
  if (path) document.getElementById(id).value = path;
}
function log(msg, cls) {
  const el = document.getElementById('log');
  const line = document.createElement('div');
  if (cls) line.className = cls;
  line.textContent = msg;
  el.appendChild(line);
  el.scrollTop = el.scrollHeight;
}
function setBusy(busy) {
  document.getElementById('start').disabled = busy;
  document.getElementById('start').textContent = busy ? "Working…" : "▶ Start";
}
async function startScan() {
  const videosOnly = document.getElementById('videos-only').checked;
  const stills = document.getElementById('stills').value;
  const videos = document.getElementById('videos').value;
  const out = document.getElementById('output').value;
  const provider = document.getElementById('provider').value;
  const apiKey = document.getElementById('api-key').value;

  if (!videos) { log('⚠ Pick a videos folder first', 'warn'); return; }
  if (!videosOnly && !stills) { log('⚠ Pick a stills folder or check Videos-only', 'warn'); return; }
  if (!out) { log('⚠ Pick an output folder first', 'warn'); return; }

  setBusy(true);
  log('Starting scan…', 'ok');
  try {
    const result = await window.pywebview.api.scan(stills, videos, out, videosOnly, provider, apiKey);
    if (result.ok) {
      log('✓ Scan complete. Opening review…', 'ok');
      window.pywebview.api.open_review();
    } else {
      log('✗ ' + (result.error || 'Scan failed'), 'err');
      setBusy(false);
    }
  } catch (e) {
    log('✗ ' + e, 'err');
    setBusy(false);
  }
}
async function openLastReview() {
  const out = document.getElementById('output').value;
  if (!out) { log('⚠ Pick an output folder first', 'warn'); return; }
  window.pywebview.api.open_review();
}
// Default output dir
window.addEventListener('DOMContentLoaded', () => {
  window.pywebview.api.default_output_dir().then(d => {
    document.getElementById('output').value = d;
  });
});
// Python -> JS log injection
window.zvr_log = log;
</script>
</body>
</html>
"""


class Api:
    """JS↔Python bridge. JS calls these via `window.pywebview.api.*`."""

    def __init__(self):
        self.window: Optional[webview.Window] = None
        self.output_dir: Optional[str] = None
        self.operation: str = "rename"
        self._dataset: dict = {}

    # ----------------------------- helpers -----------------------------

    def _log(self, msg: str, cls: str = ""):
        """Push a line to the form's log area (if the form is showing)."""
        if not self.window:
            return
        safe = json.dumps(msg)
        cls_safe = json.dumps(cls)
        try:
            self.window.evaluate_js(f"window.zvr_log && window.zvr_log({safe}, {cls_safe});")
        except Exception:
            pass

    # ----------------------------- exposed -----------------------------

    def default_output_dir(self) -> str:
        return os.path.join(os.path.expanduser("~"), "Desktop", "video-rename-review")

    def pick_folder(self) -> Optional[str]:
        result = self.window.create_file_dialog(webview.FOLDER_DIALOG)
        if isinstance(result, (list, tuple)) and result:
            return result[0]
        return None

    def open_review(self) -> None:
        if not self.output_dir:
            return
        html_path = os.path.join(self.output_dir, "index.html")
        if os.path.exists(html_path):
            self.window.load_url("file://" + html_path)

    def go_home(self) -> None:
        """Called from the review UI to navigate back to the form."""
        self.window.load_html(FORM_HTML)

    def scan(self, stills_dir: str, videos_dir: str, out_dir: str,
             videos_only: bool, provider: str, api_key: str) -> dict:
        """Run scan synchronously (blocks JS promise until done).

        Returns {ok: bool, error?: str}. The form's JS calls open_review()
        on success to navigate to the review HTML in the same window.
        """
        try:
            self.output_dir = os.path.abspath(out_dir)
            self.operation = "rename"  # Set later via API call if user changes dropdown
            os.makedirs(os.path.join(self.output_dir, "thumbs", "stills"), exist_ok=True)
            os.makedirs(os.path.join(self.output_dir, "thumbs", "videos"), exist_ok=True)

            if videos_only:
                self._log("Videos-only mode (catalog).")
                stills_index = {}
                videos = scan_videos(videos_dir, recursive=True)
                self._log(f"Found {len(videos)} videos.")
                matches = scan_videos_only(videos)
                unmatched = []
            else:
                self._log("Scanning stills…")
                stills_index = scan_stills(stills_dir, recursive=True)
                self._log(f"Found {sum(len(v) for v in stills_index.values())} stills across {len(stills_index)} stubs.")
                self._log("Scanning videos…")
                videos = scan_videos(videos_dir, recursive=True)
                self._log(f"Found {len(videos)} videos.")
                self._log("Matching…")
                matches, unmatched = match_videos_to_stills(stills_index, videos)
                self._log(f"Matched {len(matches)} stubs; {len(unmatched)} unmatched.")

            def picker(stills):
                return pick_canonical_still(stills)

            dataset = ui.matches_to_ui_dataset(
                matches, stills_root=(stills_dir or videos_dir), videos_root=videos_dir,
                project_root=self.output_dir, canonical_picker=picker,
                suggested_names={},
            )
            dataset["mode"] = "videos-only" if videos_only else "stills+videos"
            if not videos_only:
                for entry in dataset["entries"]:
                    if entry.get("canonical_still_rel"):
                        stem = os.path.splitext(os.path.basename(entry["canonical_still_rel"]))[0]
                        cleaned = naming.name_from_still_filename(stem + ".png")
                        if naming.looks_like_descriptive_name(cleaned):
                            entry["suggested_name"] = cleaned

            if videos_only:
                self._log("Extracting 3 frames per video…")
                three_dir = os.path.join(self.output_dir, "thumbs", "video_frames")
                os.makedirs(three_dir, exist_ok=True)
                ok = 0
                for e in dataset["entries"]:
                    vid = e["videos"][0]
                    src = next((v.abs_path for v in videos if v.filename == vid["filename"]), None)
                    if not src:
                        continue
                    frames = extract_three_frames(src, three_dir, e["id"])
                    if frames.get("mid"):
                        e["still_thumb"] = os.path.relpath(frames["mid"], self.output_dir)
                        e["canonical_still_rel"] = e["still_thumb"]
                        ok += 1
                    e["_video_frames"] = {k: os.path.relpath(p, self.output_dir) for k, p in frames.items()}
                self._log(f"3-frame extraction OK for {ok}/{len(dataset['entries'])}.")

            # Save matches.json
            matches_path = os.path.join(self.output_dir, "matches.json")
            with open(matches_path, "w") as f:
                json.dump(dataset, f, indent=2, default=str)

            # Still + video thumbnails
            if not videos_only:
                self._log("Generating still thumbnails…")
                still_tasks = []
                for e in dataset["entries"]:
                    if not e["canonical_still_rel"]:
                        continue
                    src = next((s.abs_path for s in stills_index.get(e["stub"], [])
                                if os.path.relpath(s.abs_path, self.output_dir) == e["canonical_still_rel"]), None)
                    if not src and stills_index.get(e["stub"]):
                        src = stills_index[e["stub"]][0].abs_path
                    if src:
                        still_tasks.append((src, os.path.join(self.output_dir, e["still_thumb"])))
                ok_n, fail_n = batch_make_still_thumbs(still_tasks, max_workers=4)
                self._log(f"Stills: {ok_n} ok, {fail_n} failed.")

            self._log("Extracting video frame previews…")
            vid_tasks = []
            for e in dataset["entries"]:
                for v in e["videos"]:
                    src = next((vid.abs_path for vid in videos if vid.filename == v["filename"]), None)
                    if src:
                        vid_tasks.append((src, os.path.join(self.output_dir, v["thumb"]), 0.5))
            ok_n, fail_n = batch_extract_video_frames(vid_tasks, max_workers=4)
            self._log(f"Video previews: {ok_n} ok, {fail_n} failed.")

            # AI naming (optional)
            if provider and api_key:
                self._log(f"Calling {provider} for descriptive names…")
                try:
                    from .ai import get_client
                    from .ai.base import VIDEO_NAMING_PROMPT
                    client = get_client(provider, api_key=api_key)
                    raw_names: dict = {}
                    if videos_only:
                        items_multi = []
                        for e in dataset["entries"]:
                            if e.get("_video_frames"):
                                paths = [os.path.join(self.output_dir, p) for p in e["_video_frames"].values() if p]
                                paths = [p for p in paths if os.path.exists(p)]
                                if paths:
                                    items_multi.append((e["id"], paths))
                        if items_multi:
                            raw_names = naming.ai_name_batch_multi(
                                client, items_multi, prompt=VIDEO_NAMING_PROMPT, max_workers=3)
                    else:
                        items = [(e["id"], os.path.join(self.output_dir, e["still_thumb"]))
                                 for e in dataset["entries"]
                                 if e["still_thumb"] and os.path.exists(os.path.join(self.output_dir, e["still_thumb"]))]
                        raw_names = naming.ai_name_batch(client, items, max_workers=3)
                    final = naming.disambiguate_names(raw_names)
                    for e in dataset["entries"]:
                        if e["id"] in final:
                            e["suggested_name"] = final[e["id"]]
                    self._log(f"AI proposed {len(final)} names.")
                except Exception as e:
                    self._log(f"AI naming failed: {e}", "err")

            # Re-save matches.json with AI names + video_frames
            with open(matches_path, "w") as f:
                json.dump(dataset, f, indent=2, default=str)

            # Generate the review HTML
            ui.write_review_html(dataset, os.path.join(self.output_dir, "index.html"))

            self._dataset = dataset
            return {"ok": True, "entries": len(dataset["entries"])}
        except Exception as e:
            self._log(f"✗ Scan failed: {e}", "err")
            import traceback
            self._log(traceback.format_exc()[:1000], "err")
            return {"ok": False, "error": str(e)}

    def apply_renames(self, approvals: dict, operation: str = "rename") -> dict:
        """Apply renames given the approvals dict (sent from the review UI's
        Approve & Rename button via the JS bridge).

        Returns {ok, succeeded, failed, undo_log}.
        """
        try:
            if not self.output_dir:
                return {"ok": False, "error": "No project folder."}

            # Resolve project-rel paths to absolute (same as cli.cmd_apply)
            by_rel = {}
            with open(os.path.join(self.output_dir, "matches.json")) as f:
                ds = json.load(f)
            for e in ds["entries"]:
                for v in e["videos"]:
                    by_rel[v["rel_path"]] = v["abs_path"]
                for s in e["all_still_files"]:
                    by_rel[s["rel_path"]] = s["abs_path"]

            for entry in approvals.get("approved", []):
                for r in entry.get("renames", []):
                    if r.get("skip"):
                        continue
                    abs_src = by_rel.get(r["from"])
                    if abs_src:
                        r["from"] = abs_src
                    src_path = r["from"]
                    if os.path.isabs(src_path):
                        new_filename = os.path.basename(r["to"])
                        r["to"] = os.path.join(os.path.dirname(src_path), new_filename)

            plan = apply_mod.build_plan(approvals, project_root=self.output_dir)
            if plan.collisions:
                return {"ok": False, "error": f"{len(plan.collisions)} target-path collisions — fix names first."}
            if plan.missing_sources:
                return {"ok": False, "error": f"{len(plan.missing_sources)} source files missing."}

            if operation not in ("rename", "copy", "move"):
                operation = "rename"

            ok, failed, undo_path = apply_mod.execute_plan(plan, undo_log_dir=self.output_dir, operation=operation)
            return {"ok": True, "succeeded": ok, "failed": failed, "undo_log": undo_path,
                    "operation": operation}
        except Exception as e:
            import traceback
            return {"ok": False, "error": str(e), "traceback": traceback.format_exc()[:1500]}


def main():
    api = Api()
    window = webview.create_window(
        f"ZohoVideoRenamer {__version__}",
        html=FORM_HTML,
        js_api=api,
        width=820, height=820, min_size=(720, 700),
        background_color="#0f0f12",
    )
    api.window = window
    webview.start(debug=False)


if __name__ == "__main__":
    main()
